name: env_LLMzCor
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib-inline
  - ipykernel
  - jupyter_client
  - jupyter_core
  - transformers
  - torch
  - SQLAlchemy
  - openpyxl
  - pillow
  - tqdm
  - requests
  - pyyaml
  - python-dotenv
  - sympy
  - joblib
  - langchain-core
  - pip
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - annotated-types
      - anyio
      - asttokens
      - charset-normalizer
      - colorama
      - comm
      - dataclasses-json
      - debugpy
      - decorator
      - et_xmlfile
      - executing
      - filelock
      - frozenlist
      - fsspec
      - greenlet
      - h11
      - httpcore
      - httpx
      - httpx-sse
      - huggingface-hub
      - idna
      - jedi
      - jsonpatch
      - jsonpointer
      - langchain-community
      - langchain-huggingface
      - langchain-text-splitters
      - langsmith
      - marshmallow
      - mpmath
      - multidict
      - mypy-extensions
      - nest-asyncio
      - networkx
      - orjson
      - packaging
      - parso
      - platformdirs
      - prompt_toolkit
      - propcache
      - psutil
      - pure_eval
      - pydantic
      - pydantic-settings
      - pydantic_core
      - Pygments
      - python-dateutil
      - regex
      - requests-toolbelt
      - safetensors
      - sentence-transformers
      - setuptools
      - six
      - sniffio
      - stack-data
      - tenacity
      - threadpoolctl
      - tokenizers
      - tornado
      - traitlets
      - typing-inspect
      - typing_extensions
      - tzdata
      - wcwidth
      - yarl
